version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  synpress-test:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "18.12"
      - run:
          name: Install Chrome
          command: brew install google-chrome
          no_output_timeout: 30m
      - run:
          name: Install deps
          command: yarn
          no_output_timeout: 30m
      - run:
          name: Build
          command: yarn build
          no_output_timeout: 30m
      - run:
          name: Test
          command: yarn test:web
          no_output_timeout: 30m

workflows:
  test_my_app:
    jobs:
      - synpress-test
