version: 2.1
orbs:
  node: circleci/node@5.0.3

executors:
  macos-executor:
    macos:
      xcode: 13.4.1

jobs:
  deps:
    executor: macos-executor
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "18.12"
      - run:
          name: Install Chrome
          command: brew install google-chrome
          no_output_timeout: 30m
      - run:
          name: Install deps
          command: yarn
          no_output_timeout: 30m

  build:
    executor: macos-executor
    steps:
      - run:
          name: Build
          command: yarn build
          no_output_timeout: 30m
      - run:
          name: Test
          command: yarn test:web
          no_output_timeout: 30m
      - store_artifacts:
          path: /Users/distiller/project/apps/web/tests/e2e/screenshots/
      - store_artifacts:
          path: /Users/distiller/project/apps/web/tests/e2e/videos/

  test:
    executor: macos-executor
    steps:
      - run:
          name: Test
          command: yarn test:web
          no_output_timeout: 30m
      - store_artifacts:
          path: /Users/distiller/project/apps/web/tests/e2e/screenshots/
      - store_artifacts:
          path: /Users/distiller/project/apps/web/tests/e2e/videos/

  store_results:
    executor: macos-executor
    steps:
      - store_artifacts:
          path: /Users/distiller/project/apps/web/tests/e2e/screenshots/
      - store_artifacts:
          path: /Users/distiller/project/apps/web/tests/e2e/videos/

workflows:
  synpress-e2e:
    jobs:
      - deps
      - build:
          requires:
            - deps
      - test:
          requires:
            - build
      - store_results:
          requires:
            - test
