version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
  codecov: codecov/codecov@1.2.3 #

executors:
  with-chrome:
    docker:
      - image: "cypress/browsers:node18.12.0-chrome107"
    resource_class: large

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Commands ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
commands:
  report-coverage:
    description: |
      Store coverage report as an artifact and send it to Codecov service.
    steps:
      - store_artifacts:
          path: coverage
      - run: npx nyc report --reporter=text || true
      - codecov/upload:
          file: coverage/coverage-final.json

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
linux-workflow: &linux-workflow
  jobs:
    # Setup
    - cypress/install:
        name: "Setup Linux"
        yarn: true
        executor: with-chrome
        build: "yarn build"

    # Run E2E tests in Chrome
    - cypress/run:
        name: "UI Tests - Chrome"
        browser: chrome
        spec: apps/web/tests/e2e/specs/*
        executor: with-chrome
        wait-on: "http://localhost:3000"
        yarn: true
        start: yarn test:web
        record: true
        parallel: true
        parallelism: 5
        ci-build-id: ${CIRCLE_SHA1:0:8}
        group: "UI - Chrome"
        requires:
          - Setup Linux
        post-steps:
          - report-coverage

workflows:
  linux:
    <<: *linux-workflow
