name: Cypress tests
on:
  push:
    branches:
      - "main"
      - "staging"
      - "cypress"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test:web
        env:
          SECRET_WORDS: "test test test test test test test test test test test junk"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          DETECTIVE_URL: ${{ secrets.DETECTIVE_URL }}
          ROUNDUP_ENABLED: ${{ secrets.ROUNDUP_ENABLED }}
          POSTMARK_TOKEN: ${{ secrets.POSTMARK_TOKEN }}
