name: run my vanilla Cypress tests
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          install-command: yarn --frozen-lockfile --prefer-offline --no-audit
          command: yarn test:e2e:ci
